# see : https://github.com/mojombo/jekyll/wiki/Configuration
safe: false
auto: false
server: false
server_port: 4000
baseurl: /

source: ./
destination: ./_site
plugins: ./_plugins

future: true
lsi: false
pygments: true
markdown: maruku
exclude: 
        - .git
        - .gitignore
        - .sass-cache
        - .DS_STORE
        - _posts
        - _layouts
        - _includes
        - _config.yml
        - scss
        - Rakefile
        - Gruntfile.js
        - node_modules
        - package.json
        - README.md
paginate : 10

maruku:
  use_tex: false
  use_divs: false
  png_engine: blahtex
  png_dir: images/latex
  png_url: /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

# see : https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

# all variables can be referred in templates
title:        Caffeine
author:       Zypeh
description:  'Daytime Geek | Caffeine Addiction'
name :        Caffeine
availability: free
email:        ciboy2011@gmail.com
feed:         feed/
